/* test_fixture_parity.c — Compare CPU/CUDA ops against Python golden reference.
 *
 * Loads .bin fixture files generated by tests/fixtures/gen_op_fixtures.py,
 * builds identical ggml graphs, computes on CPU and CUDA, then compares
 * against the Python reference output.
 *
 * This catches CUDA numeric bugs that CPU-vs-CUDA comparison misses
 * when both implementations share the same bug.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <math.h>
#include <inttypes.h>
#include <errno.h>

#include "ggml.h"
#include "ggml-cpu.h"
#include "ggml_backend.h"
#include "voxcpm.h"
#include "minicpm4.h"

/* ---- Test accounting ---- */
static int n_pass = 0, n_fail = 0, n_skip = 0;

#define ANSI_GREEN  "\033[32m"
#define ANSI_RED    "\033[31m"
#define ANSI_YELLOW "\033[33m"
#define ANSI_RESET  "\033[0m"

static void pass(const char * fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    printf("  " ANSI_GREEN "PASS:" ANSI_RESET " ");
    vprintf(fmt, ap);
    printf("\n");
    va_end(ap);
    n_pass++;
}

static void fail(const char * fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "  " ANSI_RED "FAIL:" ANSI_RESET " ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    n_fail++;
}

static void skip(const char * msg) {
    printf("  " ANSI_YELLOW "SKIP:" ANSI_RESET " %s\n", msg);
    n_skip++;
}

/* ---- Binary fixture loader ---- */
#ifndef FIXTURE_DIR
#define FIXTURE_DIR "tests/fixtures"
#endif

static char * fixture_path(const char * name) {
    /* $FIXTURE_DIR overrides compile-time default */
    static const char * dir = NULL;
    if (!dir) {
        dir = getenv("FIXTURE_DIR");
        if (!dir) dir = FIXTURE_DIR;
        fprintf(stderr, "DEBUG FIXTURE_DIR=%s\n", dir);
    }
    size_t dlen = strlen(dir);
    size_t nlen = strlen(name);
    char * path = (char *)malloc(dlen + 1 + nlen + 1);
    if (!path) return NULL;
    memcpy(path, dir, dlen);
    path[dlen] = '/';
    memcpy(path + dlen + 1, name, nlen + 1);
    return path;
}

static float * load_bin(const char * name, size_t * n_out) {
    char * path = fixture_path(name);
    if (!path) return NULL;
    FILE * f = fopen(path, "rb");
    free(path);
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long nbytes = ftell(f);
    rewind(f);
    if (nbytes <= 0 || nbytes % sizeof(float) != 0) {
        fclose(f);
        return NULL;
    }
    size_t n = (size_t)nbytes / sizeof(float);
    float * data = (float *)malloc(n * sizeof(float));
    if (!data) { fclose(f); return NULL; }
    size_t read = fread(data, sizeof(float), n, f);
    fclose(f);
    if (read != n) { free(data); return NULL; }
    *n_out = n;
    return data;
}

/* ---- Backend helpers ---- */
typedef struct {
    struct ggml_context * ctx;
    struct ggml_cgraph  * graph;
} test_graph;

static int compute_cpu(struct ggml_context * ctx, struct ggml_cgraph * graph) {
    return ggml_graph_compute_with_ctx(ctx, graph, 1);
}

static int compute_cuda(struct ggml_context * ctx, struct ggml_cgraph * graph) {
    vcpm_backend be;
    memset(&be, 0, sizeof(be));
    int ret = vcpm_backend_init(&be, VCPM_BACKEND_CUDA, 1);
    if (ret != 0) { return -1; }
    ret = vcpm_backend_compute_graph(&be, ctx, graph, 1);
    vcpm_backend_free(&be);
    return ret;
}

/* ---- Comparison ---- */
static double cosine_sim(const float * a, const float * b, int n) {
    double dot = 0, na = 0, nb = 0;
    for (int i = 0; i < n; i++) {
        dot += (double)a[i] * b[i];
        na  += (double)a[i] * a[i];
        nb  += (double)b[i] * b[i];
    }
    return dot / (sqrt(na) * sqrt(nb) + 1e-30);
}

static double rmse(const float * a, const float * b, int n) {
    double s = 0;
    for (int i = 0; i < n; i++)
        s += ((double)a[i] - b[i]) * ((double)a[i] - b[i]);
    return sqrt(s / n);
}

/* ---- Helpers: create a 2D tensor from flat data ---- */
static struct ggml_tensor * tensor_from_2d(struct ggml_context * ctx,
                                            int64_t ne0, int64_t ne1,
                                            const float * data) {
    struct ggml_tensor * t = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, ne0, ne1);
    memcpy(t->data, data, (size_t)ne0 * ne1 * sizeof(float));
    return t;
}

/* Load row-major numpy data [nrows, ncols] into column-major ggml tensor [nrows, ncols].
 * Row-major: data[i * ncols + j] = matrix[i, j].
 * Column-major ggml: element [i, j] at offset i + j*nrows.
 * We rearrange: dst[j * nrows + i] = src[i * ncols + j] */
static struct ggml_tensor * tensor_from_2d_rowmajor(struct ggml_context * ctx,
                                                      int64_t nrows, int64_t ncols,
                                                      const float * data) {
    struct ggml_tensor * t = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, nrows, ncols);
    float * dst = (float *)t->data;
    for (int64_t i = 0; i < nrows; i++)
        for (int64_t j = 0; j < ncols; j++)
            dst[j * nrows + i] = data[i * ncols + j];
    return t;
}

static struct ggml_tensor * tensor_from_1d(struct ggml_context * ctx,
                                            int64_t ne0,
                                            const float * data) {
    struct ggml_tensor * t = ggml_new_tensor_1d(ctx, GGML_TYPE_F32, ne0);
    memcpy(t->data, data, (size_t)ne0 * sizeof(float));
    return t;
}

/* ---- Test: RMS Norm (plain) ---- */
static void test_fixture_rms_norm(void) {
    printf("\n============================================\n");
    printf("  Fixture: RMS Norm (plain)\n");
    printf("============================================\n");

    size_t n;
    float * input  = load_bin("rms_norm_plain_input.bin", &n);
    float * golden = load_bin("rms_norm_plain_output.bin", &n);
    if (!input || !golden) { fail("Failed to load fixture"); free(input); free(golden); return; }

    int hidden = 8, n_tokens = 4;
    int total = hidden * n_tokens;

    for (int mode = 0; mode < 2; mode++) {
        const char * label = (mode == 0) ? "CPU" : "CUDA";
        struct ggml_init_params params = { .mem_size = 64*1024*1024, .mem_buffer = NULL, .no_alloc = false };
        struct ggml_context * ctx = ggml_init(params);
        struct ggml_tensor * x = tensor_from_2d(ctx, hidden, n_tokens, input);
        struct ggml_tensor * y = ggml_rms_norm(ctx, x, 1e-6f);
        struct ggml_cgraph * graph = ggml_new_graph(ctx);
        ggml_build_forward_expand(graph, y);
        int ret = (mode == 0) ? compute_cpu(ctx, graph) : compute_cuda(ctx, graph);
        if (ret != 0) { fail("%s compute failed", label); ggml_free(ctx); continue; }
        float * out = (float *)y->data;
        double cos = cosine_sim(golden, out, total);
        double rms = rmse(golden, out, total);
        if (cos >= 0.9999f && rms <= 0.01f)
            pass("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
        else
            fail("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
        ggml_free(ctx);
    }
    free(input); free(golden);
}

/* ---- Test: RMS Norm (weighted) ---- */
static void test_fixture_rms_norm_weighted(void) {
    printf("\n============================================\n");
    printf("  Fixture: RMS Norm (weighted)\n");
    printf("============================================\n");

    size_t n;
    float * input  = load_bin("rms_norm_weighted_input.bin", &n);
    float * golden = load_bin("rms_norm_weighted_output.bin", &n);
    float * weight = load_bin("rms_norm_weighted_weight.bin", &n);
    if (!input || !golden || !weight) { fail("Failed to load fixture"); free(input); free(golden); free(weight); return; }

    int hidden = 8, n_tokens = 4;
    int total = hidden * n_tokens;

    for (int mode = 0; mode < 2; mode++) {
        const char * label = (mode == 0) ? "CPU" : "CUDA";
        struct ggml_init_params params = { .mem_size = 64*1024*1024, .mem_buffer = NULL, .no_alloc = false };
        struct ggml_context * ctx = ggml_init(params);
        struct ggml_tensor * x = tensor_from_2d(ctx, hidden, n_tokens, input);
        struct ggml_tensor * y = ggml_rms_norm(ctx, x, 1e-6f);
        struct ggml_tensor * w = tensor_from_1d(ctx, hidden, weight);
        y = ggml_mul(ctx, y, w);
        struct ggml_cgraph * graph = ggml_new_graph(ctx);
        ggml_build_forward_expand(graph, y);
        int ret = (mode == 0) ? compute_cpu(ctx, graph) : compute_cuda(ctx, graph);
        if (ret != 0) { fail("%s compute failed", label); ggml_free(ctx); continue; }
        float * out = (float *)y->data;
        double cos = cosine_sim(golden, out, total);
        double rms = rmse(golden, out, total);
        if (cos >= 0.9999f && rms <= 0.01f)
            pass("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
        else {
            fail("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
            if (mode == 1) {
                fprintf(stderr, "DBG wted: golden=");
                for (int d=0; d<total; d++) fprintf(stderr, " %+.6f", golden[d]);
                fprintf(stderr, "\nDBG wted: weight=");
                for (int d=0; d<hidden; d++) fprintf(stderr, " %+.6f", weight[d]);
                fprintf(stderr, "\nDBG wted: out=");
                for (int d=0; d<total; d++) fprintf(stderr, " %+.6f", out[d]);
                fprintf(stderr, "\n");
            }
        }

        /* Check token differentiation */
        int diff = 0;
        for (int h = 0; h < hidden; h++)
            if (out[h] != out[(n_tokens-1)*hidden + h])
                { diff = 1; break; }
        if (!diff)
            fail("%s: all tokens identical!", label);
        else
            pass("%s: tokens differ across positions", label);

        ggml_free(ctx);
    }
    free(input); free(golden); free(weight);
}

/* ---- Test: MLP (SwiGLU) ---- */

static void test_fixture_mlp(void) {
    printf("\n============================================\n");
    printf("  Fixture: MLP (SwiGLU)\n");
    printf("============================================\n");

    size_t n;
    float * input      = load_bin("mlp_input.bin", &n);
    float * golden     = load_bin("mlp_output.bin", &n);
    float * gate_w     = load_bin("mlp_gate_weight.bin", &n);
    float * up_w       = load_bin("mlp_up_weight.bin", &n);
    float * down_w     = load_bin("mlp_down_weight.bin", &n);
    if (!input || !golden || !gate_w || !up_w || !down_w) {
        fail("Failed to load fixture"); free(input); free(golden); free(gate_w); free(up_w); free(down_w); return;
    }

    int hidden = 8, inter = 16, n_tokens = 4;
    int total = hidden * n_tokens;

    for (int mode = 0; mode < 2; mode++) {
        const char * label = (mode == 0) ? "CPU" : "CUDA";
        struct ggml_init_params params = { .mem_size = 64*1024*1024, .mem_buffer = NULL, .no_alloc = false };
        struct ggml_context * ctx = ggml_init(params);
        struct ggml_tensor * x = tensor_from_2d(ctx, hidden, n_tokens, input);

        /* ggml_mul_mat(w, x) = w^T @ x, where w has shape [in, out]
         * gate_w from fixture is stored ggml-order: column j = out_feature j
         * i.e. shape is [hidden, inter] */
        struct ggml_tensor * gw = tensor_from_2d(ctx, hidden, inter, gate_w);
        struct ggml_tensor * uw = tensor_from_2d(ctx, hidden, inter, up_w);
        struct ggml_tensor * dw = tensor_from_2d(ctx, inter, hidden, down_w);

        struct ggml_tensor * gate = ggml_silu(ctx, ggml_mul_mat(ctx, gw, x));
        struct ggml_tensor * up   = ggml_mul_mat(ctx, uw, x);
        struct ggml_tensor * prod = ggml_mul(ctx, gate, up);
        struct ggml_tensor * out  = ggml_mul_mat(ctx, dw, prod);

        struct ggml_cgraph * graph = ggml_new_graph(ctx);
        ggml_build_forward_expand(graph, out);
        int ret = (mode == 0) ? compute_cpu(ctx, graph) : compute_cuda(ctx, graph);
        if (ret != 0) { fail("%s compute failed", label); ggml_free(ctx); continue; }
        float * out_d = (float *)out->data;
        double cos = cosine_sim(golden, out_d, total);
        double rms = rmse(golden, out_d, total);
        if (cos >= 0.9999f && rms <= 0.01f)
            pass("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
        else
            fail("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);

        /* Check token differentiation */
        int diff = 0;
        for (int h = 0; h < hidden; h++)
            if (out_d[h] != out_d[(n_tokens-1)*hidden + h])
                { diff = 1; break; }
        if (!diff)
            fail("%s: all tokens identical!", label);
        else
            pass("%s: tokens differ across positions", label);

        ggml_free(ctx);
    }
    free(input); free(golden); free(gate_w); free(up_w); free(down_w);
}

/* ---- Test: Attention (synthetic, no RoPE) ---- */
static void test_fixture_attention(void) {
    printf("\n============================================\n");
    printf("  Fixture: Attention (no RoPE)\n");
    printf("============================================\n");

    size_t n;
    float * input      = load_bin("attention_input.bin", &n);
    float * golden     = load_bin("attention_output.bin", &n);
    float * q_w_data   = load_bin("attention_q_weight.bin", &n);
    float * k_w_data   = load_bin("attention_k_weight.bin", &n);
    float * v_w_data   = load_bin("attention_v_weight.bin", &n);
    float * o_w_data   = load_bin("attention_o_weight.bin", &n);
    if (!input || !golden || !q_w_data || !k_w_data || !v_w_data || !o_w_data) {
        fail("Failed to load fixture"); free(input); free(golden);
        free(q_w_data); free(k_w_data); free(v_w_data); free(o_w_data); return;
    }

    int hidden = 16, n_heads = 4, n_kv_heads = 2, head_dim = 4, n_tokens = 3;
    int kv_hidden = n_kv_heads * head_dim;  /* = 8 */
    int total = hidden * n_tokens;

    for (int mode = 0; mode < 2; mode++) {
        const char * label = (mode == 0) ? "CPU" : "CUDA";
        struct ggml_init_params params = { .mem_size = 128*1024*1024, .mem_buffer = NULL, .no_alloc = false };
        struct ggml_context * ctx = ggml_init(params);
        struct ggml_tensor * x = tensor_from_2d(ctx, hidden, n_tokens, input);

        /* Fix: use tensor_from_2d_rowmajor for all weights.
         * The fixture files store numpy row-major data [nrows, ncols].
         * We need column-major ggml tensor [nrows, ncols].
         * Square identity matrices (q_w, o_w) happened to work with memcpy
         * since identity^T = identity, but non-square (k_w, v_w) were WRONG. */
        struct ggml_tensor * q_w = tensor_from_2d_rowmajor(ctx, hidden, hidden, q_w_data);
        struct ggml_tensor * k_w = tensor_from_2d_rowmajor(ctx, hidden, kv_hidden, k_w_data);
        struct ggml_tensor * v_w = tensor_from_2d_rowmajor(ctx, hidden, kv_hidden, v_w_data);
        struct ggml_tensor * o_w = tensor_from_2d_rowmajor(ctx, hidden, hidden, o_w_data);

        int max_seq_len = 4096;
        struct ggml_tensor * k_cache = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, head_dim, n_kv_heads, max_seq_len);
        struct ggml_tensor * v_cache = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, head_dim, n_kv_heads, max_seq_len);
        memset(k_cache->data, 0, (size_t)head_dim * n_kv_heads * max_seq_len * sizeof(float));
        memset(v_cache->data, 0, (size_t)head_dim * n_kv_heads * max_seq_len * sizeof(float));
        int32_t n_used = 0;

        struct ggml_cgraph * graph = ggml_new_graph(ctx);
        struct ggml_tensor * attn_out = vcpm_attention(ctx, graph, x,
                                                          q_w, k_w, v_w, o_w,
                                                          k_cache, v_cache, &n_used,
                                                          n_heads, n_kv_heads,
                                                          head_dim, 0, 0, 1, 0);
        if (!attn_out) { fail("%s attention build failed", label); ggml_free(ctx); continue; }
        ggml_build_forward_expand(graph, attn_out);

        int ret = (mode == 0) ? compute_cpu(ctx, graph) : compute_cuda(ctx, graph);
        if (ret != 0) { fail("%s compute failed: %d", label, ret); ggml_free(ctx); continue; }

        int n_nodes = ggml_graph_n_nodes(graph);
        struct ggml_tensor * out_t = ggml_graph_node(graph, n_nodes - 1);
        if (!out_t || !out_t->data) { fail("%s output missing", label); ggml_free(ctx); continue; }

        float * out_d = (float *)out_t->data;
        double cos = cosine_sim(golden, out_d, total);
        double rms = rmse(golden, out_d, total);
        if (cos >= 0.9999f && rms <= 0.01f)
            pass("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);
        else
            fail("%s vs golden: cos=%.6f rmse=%.6f", label, cos, rms);

        ggml_free(ctx);
    }
    free(input); free(golden); free(q_w_data); free(k_w_data); free(v_w_data); free(o_w_data);
}

/* ---- Main ---- */
int main(void) {
    printf("Fixture Parity Tests: Python golden vs CPU vs CUDA\n");
    printf("==================================================\n\n");

    /* Check CUDA availability */
    vcpm_backend be;
    memset(&be, 0, sizeof(be));
    int cuda_ok = (vcpm_backend_init(&be, VCPM_BACKEND_CUDA, 1) == 0);
    if (cuda_ok) vcpm_backend_free(&be);
    if (!cuda_ok) {
        fprintf(stderr, "WARNING: CUDA unavailable — CPU-only tests\n");
    }

    test_fixture_rms_norm();
    test_fixture_rms_norm_weighted();
    test_fixture_mlp();
    test_fixture_attention();

    printf("\n==================================================\n");
    printf("  Results: %d pass, %d fail, %d skip\n", n_pass, n_fail, n_skip);
    printf("==================================================\n");

    return n_fail > 0 ? 1 : 0;
}
