# CMake generated Testfile for 
# Source directory: D:/voxcpm-cpp
# Build directory: D:/voxcpm-cpp/build_cuda
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(smoke "D:/voxcpm-cpp/build_cuda/Debug/test_smoke.exe")
  set_tests_properties(smoke PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;149;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(smoke "D:/voxcpm-cpp/build_cuda/Release/test_smoke.exe")
  set_tests_properties(smoke PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;149;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(smoke "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_smoke.exe")
  set_tests_properties(smoke PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;149;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(smoke "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_smoke.exe")
  set_tests_properties(smoke PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;149;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(smoke NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(wav "D:/voxcpm-cpp/build_cuda/Debug/test_wav.exe")
  set_tests_properties(wav PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;155;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(wav "D:/voxcpm-cpp/build_cuda/Release/test_wav.exe")
  set_tests_properties(wav PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;155;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(wav "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_wav.exe")
  set_tests_properties(wav PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;155;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(wav "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_wav.exe")
  set_tests_properties(wav PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;155;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(wav NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(wav_writer "D:/voxcpm-cpp/build_cuda/Debug/test_wav_writer.exe")
  set_tests_properties(wav_writer PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;161;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(wav_writer "D:/voxcpm-cpp/build_cuda/Release/test_wav_writer.exe")
  set_tests_properties(wav_writer PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;161;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(wav_writer "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_wav_writer.exe")
  set_tests_properties(wav_writer PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;161;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(wav_writer "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_wav_writer.exe")
  set_tests_properties(wav_writer PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;161;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(wav_writer NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(sequence "D:/voxcpm-cpp/build_cuda/Debug/test_sequence.exe")
  set_tests_properties(sequence PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;167;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(sequence "D:/voxcpm-cpp/build_cuda/Release/test_sequence.exe")
  set_tests_properties(sequence PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;167;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(sequence "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_sequence.exe")
  set_tests_properties(sequence PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;167;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(sequence "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_sequence.exe")
  set_tests_properties(sequence PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;167;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(sequence NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(minicpm4 "D:/voxcpm-cpp/build_cuda/Debug/test_minicpm4.exe")
  set_tests_properties(minicpm4 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;175;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(minicpm4 "D:/voxcpm-cpp/build_cuda/Release/test_minicpm4.exe")
  set_tests_properties(minicpm4 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;175;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(minicpm4 "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_minicpm4.exe")
  set_tests_properties(minicpm4 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;175;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(minicpm4 "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_minicpm4.exe")
  set_tests_properties(minicpm4 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;175;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(minicpm4 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(phase5 "D:/voxcpm-cpp/build_cuda/Debug/test_phase5.exe")
  set_tests_properties(phase5 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;183;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(phase5 "D:/voxcpm-cpp/build_cuda/Release/test_phase5.exe")
  set_tests_properties(phase5 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;183;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(phase5 "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_phase5.exe")
  set_tests_properties(phase5 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;183;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(phase5 "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_phase5.exe")
  set_tests_properties(phase5 PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;183;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(phase5 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(model_loader_tensors "D:/voxcpm-cpp/build_cuda/Debug/test_model_loader_tensors.exe")
  set_tests_properties(model_loader_tensors PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;189;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(model_loader_tensors "D:/voxcpm-cpp/build_cuda/Release/test_model_loader_tensors.exe")
  set_tests_properties(model_loader_tensors PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;189;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(model_loader_tensors "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_model_loader_tensors.exe")
  set_tests_properties(model_loader_tensors PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;189;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(model_loader_tensors "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_model_loader_tensors.exe")
  set_tests_properties(model_loader_tensors PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;189;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(model_loader_tensors NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(tokenizer_parity "D:/voxcpm-cpp/build_cuda/Debug/test_tokenizer_parity.exe" "voxcpm2_v2_full.gguf")
  set_tests_properties(tokenizer_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;196;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(tokenizer_parity "D:/voxcpm-cpp/build_cuda/Release/test_tokenizer_parity.exe" "voxcpm2_v2_full.gguf")
  set_tests_properties(tokenizer_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;196;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(tokenizer_parity "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_tokenizer_parity.exe" "voxcpm2_v2_full.gguf")
  set_tests_properties(tokenizer_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;196;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(tokenizer_parity "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_tokenizer_parity.exe" "voxcpm2_v2_full.gguf")
  set_tests_properties(tokenizer_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;196;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(tokenizer_parity NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cfm_parity "D:/voxcpm-cpp/build_cuda/Debug/test_cfm_parity.exe" "voxcpm2_v2_full.gguf" "fixtures/ref")
  set_tests_properties(cfm_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;205;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cfm_parity "D:/voxcpm-cpp/build_cuda/Release/test_cfm_parity.exe" "voxcpm2_v2_full.gguf" "fixtures/ref")
  set_tests_properties(cfm_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;205;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cfm_parity "D:/voxcpm-cpp/build_cuda/MinSizeRel/test_cfm_parity.exe" "voxcpm2_v2_full.gguf" "fixtures/ref")
  set_tests_properties(cfm_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;205;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cfm_parity "D:/voxcpm-cpp/build_cuda/RelWithDebInfo/test_cfm_parity.exe" "voxcpm2_v2_full.gguf" "fixtures/ref")
  set_tests_properties(cfm_parity PROPERTIES  LABELS "model" _BACKTRACE_TRIPLES "D:/voxcpm-cpp/CMakeLists.txt;205;add_test;D:/voxcpm-cpp/CMakeLists.txt;0;")
else()
  add_test(cfm_parity NOT_AVAILABLE)
endif()
subdirs("_deps/ggml-build")
